# This file contains the default values for variables used in the role
vcpu_count: 14
memory_size: 16384
cpu_pinning:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
isolated_cores: 1-7,9-15
