# host_vars/my-vm.yml

ansible_ssh_private_key_file: /tmp/vm_ssh_key

node_total_estimator: "true"
node_components_estimator: "true"
model_server_enable: "false"
model_server_url: "http://model-server:8100"
node_total_init_url: "https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.7/specpower-0.7.11/acpi/AbsPower/BPFOnly/SGDRegressorTrainer_0.zip"
node_components_init_url: "https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.7/ec2-0.7.11/rapl-sysfs/AbsPower/BPFOnly/SGDRegressorTrainer_0.zip"
model_server_entrypoint: "python3.10 quay.io/sustainable_computing_io/kepler_model_server:v0.7.11-2"
local_model_directory: "/tmp/trained-equinix-models/"
vm_model_directory: "/tmp/models/trained-equinix-models"
http_port: 8080
