name: 'Setup Runner Action'
description: 'Composite Action to Setup Metal Runner'
runs:
  using: 'composite'
  steps:
    - name: Setup runner
      shell: bash
      run: |
        echo "This is runner: ${{ runner.name }}"
        echo "Running on ${{ runner.arch }} ${{ runner.os }}"
        # config ssh
        sudo ssh-keygen -t rsa -b 4096 -f /root/.ssh/ansible_rsa -N ''
        sudo cat ~/.ssh/ansible_rsa.pub >> ~/.ssh/authorized_keys
        sudo echo -n "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrMUcsN9rhYacFimRyOrqPUdYH4SZASH6wqK/cRsKccNcj/nP4TtxaacB5J3/Rmy61f6IzZWIqoU+KyKLCJk+2/JAMRSbjAhnIiKgbWfhL9Fsqs4XosSAGC8+F3hdPZ1SD3rdu66dbk0odKX3bhzAtyOguMvp65eJc19x/5XLrmmucZI6WLg5SvHlIVCG3qunvTkO+OoJwPKEg9AD6Tazca2qGKJtONNy370SfXyIjs6EeNvZlszXd0AS5oH/xg0Ok5Ru2I0G3gR0GESo3wg75RMLWC9bA3LI7ymaO3oMcOYvxldZln/ngSsQ6k0P+Rq3fPdPMPqtb5T8gQVYdDLGxZvk1VIRh4R69zDUbOyeWQU/49K+7pDi/GOfjjRpzskE6nluCAY58iUz1CNgTg8bVrMn8pId8sf//7J/kNIs+5zt1uicjDObSuYZpbq5qR0+4stSi3NZWYBbvll8Es8wa+lDqdH0dR/00ELqjTbmuxf1p1rJhsnrvV6acW/+7jEc= vibhuprashar@vprashar-mac" >> ~/.ssh/authorized_keys
        sudo echo "StrictHostKeyChecking no" >> ~/.ssh/config
        # install ansible
        if grep -q 'Ubuntu' /etc/os-release ; then
          sudo apt update -y
          sudo apt install software-properties-common -y
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible python3-pip
        else
          sudo dnf -y install ansible-core python3-pip
          sudo dnf install -y rhel-system-roles
        fi
        sudo ansible-galaxy collection install prometheus.prometheus
        sudo ansible-galaxy collection install community.crypto
        sudo ansible-galaxy collection install community.libvirt
        sudo ansible-config init --disabled | sed "s/;host_key_checking=True/host_key_checking=False/g" | sed "s/;private_key_file=/private_key_file=~\/.ssh\/ansible_rsa/g" | sed 's|;roles_path={{ ANSIBLE_HOME ~ "/roles:/usr/share/ansible/roles:/etc/ansible/roles" }}|roles_path={{ ANSIBLE_HOME ~ "/roles:/usr/share/ansible/roles:/etc/ansible/roles;/root/.ansible/collections/ansible_collections/community/libvirt/roles" }}|' > /etc/ansible/ansible.cfg
