# group_vars/all.yml
firewall:
  - service: pmcd
    state: enabled
  - service: grafana
    state: enabled
metrics_retention_days: 7
metrics_graph_service: yes
metrics_query_service: yes
metrics_monitored_hosts: "{{ groups['servers'] }}"
