---
- name: Create systemd service file for node_exporter
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/{{ node_exporter_service }}.service
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  notify:
    - Restart node_exporter
