---
- name: Create node_exporter user
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    shell: /sbin/nologin

- name: Download node_exporter binary
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz

- name: Extract node_exporter binary
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move node_exporter binary to bin directory
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_bin_dir }}/node_exporter"
    mode: '0755'
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"

- name: Cleanup
  ansible.builtin.file:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64
    state: absent

- name: Cleanup tar file
  ansible.builtin.file:
    path: /tmp/node_exporter.tar.gz
    state: absent
