---
# This file contains variables that are less likely to be overridden
kepler_repo: https://github.com/sustainable-computing-io/kepler.git
kepler_dir: /opt/kepler
metal_compose_dir: /opt/kepler/manifests/compose/validation/metal
vm_compose_dir: /opt/kepler/manifests/compose/validation/vm
