---
- name: Run validator and handle potiental errors
  block:
    - name: Run the validator
      ansible.builtin.shell: |
        cd {{ validator_dir }}
        hatch run validator --config-file=validator-regression.yaml regression
      register: validator_output

    - name: Show validator output
      ansible.builtin.debug:
        msg: "{{ validator_output.stdout.splitlines() }}"

  rescue:
    - name: Show validator errors
      ansible.builtin.debug:
        msg: "{{ validator_output.stderr.splitlines() }}"

    - name: Fail the role if the validator fails
      ansible.builtin.fail:
        msg: "The validator test failed. Please check the output above for more information."
