# This file contains variables that are less likely to be overridden
vcpu_count: 14
memory_size: 16384
cpu_pinning:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
isolated_cores: 1-7,9-15
vm_name: my-vm
vm_disk_path: /var/lib/libvirt/images/my-vm.qcow2
ssh_key_path: /tmp/vm_ssh_key
backup_vm_disk_path: /var/lib/libvirt/images/my-vm-bak.qcow2
vm_image_url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
vm_user: root
vm_password: ansible_password
ssh_pub_key_path: /tmp/vm_ssh_key.pub
cloud_init_config_path: /var/lib/libvirt/images/cloud_init_config.yml
common_packages:
  - qemu-kvm
  - cloud-init
  - tuned
  - python3-libvirt

ubuntu_packages:
  - libvirt-daemon-system
  - libguestfs-tools
  - virtinst
  - qemu-utils

rhel_packages:
  - libvirt
  - virt-install
  - qemu-img
  - guestfs-tools
