---
- name: Install podman
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Create Kepler systemd unit file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Podman container-kepler.service
      Documentation=man:podman-generate-systemd(1)
      Wants=network-online.target
      After=network-online.target
      RequiresMountsFor=%t/containers

      [Service]
      Environment=PODMAN_SYSTEMD_UNIT=%n
      Restart=always
      TimeoutStopSec=70
      ExecStartPre=/bin/rm -f %t/%n.ctr-id
      ExecStart=/usr/bin/podman run --cidfile=%t/%n.ctr-id --cgroups=no-conmon --rm --sdnotify=conmon -d --replace --name kepler \
          --privileged --network=host --pid=host --rm -e EXPOSE_VM_METRICS="true" -e EXCLUDE_SWAPPER_PROCESS="true" -e \
          ENABLE_PROCESS_METRICS="true" -e EXCLUDE_SWAPPER_PROCESS="true" -v /usr/src:/usr/src -v /sys/:/sys/ -v /proc:/proc -v /etc:/etc \
          {{ kepler_image }} /usr/bin/kepler --config-dir=/etc
      ExecStop=/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
      ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
      Type=notify
      NotifyAccess=all

      [Install]
      WantedBy=multi-user.target default.target
    dest: /etc/systemd/system/container-kepler.service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start Kepler service
  ansible.builtin.systemd:
    name: container-kepler
    enabled: yes
    state: started
