- name: Ensure Docker service is running
  service:
    name: docker
    state: started

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Verify Docker installation
  command: docker --version
  register: docker_version

- name: Display Docker version
  ansible.builtin.debug:
    msg: "{{ docker_version.stdout }}"
