name: 'Train Action'
description: 'Composite Action to Trains Models'
inputs:
  model_export_path:
    description: 'Location to output models'
    required: true
    default: '/tmp/trained-equinix-models'
runs:
  using: 'composite'
  steps:
    - name: Check Prometheus Endpoint
      shell: bash
      run: |
        for i in {1..10}; do
          status_code=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:9090)
          if [ "$status_code" -ne 200 ]; then
            echo "Prometheus Endpoint is inactive (status: $status_code)"
            exit 1
          else
            echo "Prometheus Endpoint is active"
          fi

          metric_response = $(curl -sG http://localhost:9090/api/v1/query --data-urlencode 'query=kepler_process_bpf_cpu_time_ms_total{job="vm"}')
          if echo "$metric_response" | grep -q '"result":\[\]'; then
            echo "Target VM Metric does not exist or is empty"
            exit 1
          else
            echo "Target VM Metric does exist and is nonempty"
          fi

    - name: Train models
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/ansible
        echo "Deploy Trainer"
        ansible-playbook -i inventory.yml -vvv model_trainer_playbook.yml -e "model_export_path=${{ inputs.model_export_path }}"
    
    - name: Upload models as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-equinix-models
        path: ${{ inputs.model_export_path }}
        retention-days: 8