name: 'Train Action'
description: 'Composite Action to Trains Models'
inputs:
  model_export_path:
    description: 'Location to output models'
    required: true
    default: '/tmp/trained-equinix-models'
runs:
  using: 'composite'
  steps:
    - name: Train models
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/ansible
        echo "Deploy Trainer"
        ansible-playbook -i inventory.yml -vvv model_trainer_playbook.yml -e "model_export_path=${{ inputs.model_export_path }}"
    
    - name: Upload models as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-equinix-models
        path: ${{ inputs.model_export_path }}
        retention-days: 8