---
- name: Clone kepler repo
  git:
    repo: "{{ kepler_repo }}"
    dest: "{{ kepler_dir }}"
    version: main

- name: Get latest commit details
  shell: |
    cd {{ kepler_dir }}
    git log -n 1

- name: Create Docker network
  shell: |
    docker network create --driver=macvlan --subnet={{ subnet }} -o parent=virbr0 virt-net
  when: ansible_hostname != "my-vm"

- name: Start Docker compose services on BM
  community.docker.docker_compose_v2:
    project_src: "{{ metal_compose_dir }}"
    build: always
    files: compose.yaml
    state: present
  environment:
    VM_IP: "{{ vm_ip }}"
  when: ansible_hostname != "my-vm"
