---
- name: Install Docker on Metal
  ansible.builtin.include_tasks: metal.yml
  when: inventory_hostname == 'localhost'

- name: Install Docker on VM
  ansible.builtin.include_tasks: vm.yml
  when: inventory_hostname == 'my-vm'

- name: Validate Docker installation
  ansible.builtin.include_tasks: validate.yml
