---
- name: Ensure necessary packages are installed on BM
  ansible.builtin.package:
    name: "{{ metal_necessary_packages }}"
    state: present
    update_cache: true

- name: Install hatch via pip
  ansible.builtin.pip:
    name: hatch
    state: latest

- name: Add Docker official GPG key
  ansible.builtin.apt_key:
    url: "{{ metal_docker_gpg_key_url }}"
    state: present

- name: Set up Docker stable repository
  ansible.builtin.apt_repository:
    repo: "{{ metal_docker_repo_url }}"
    state: present

- name: Update the apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker Engine and related packages
  ansible.builtin.apt:
    name: "{{ docker_necessary_packages }}"
    state: latest
  register: docker_install

- name: Show Output
  ansible.builtin.debug:
    var: docker_install

