- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_version

- name: Display Docker version
  ansible.builtin.debug:
    msg: "{{ docker_version.stdout }}"
