---
- name: Ensure necessary packages are installed on VM
  ansible.builtin.package:
    name: "{{ vm_necessary_packages }}"
    state: present

- name: Add Docker repository on VM
  ansible.builtin.command: dnf config-manager --add-repo {{ vm_docker_repo_url }}

- name: Install Docker on VM
  ansible.builtin.package:
    name: "{{ docker_necessary_packages }}"
    state: latest
  register: docker_install

- name: Show Output
  ansible.builtin.debug:
    var: docker_install
