---
- name: Deploy and run the Kepler Validator
  hosts: localhost
  become: yes
  vars:
    validator_repo: "https://github.com/sustainable-computing-io/kepler.git"
    validator_dir: "/opt/kepler/e2e/tools/validator"
    validator_yaml_path: "/opt/kepler/e2e/tools/validator/validator.yaml"

  tasks:
    - name: Clone the Kepler repository
      git:
        repo: "{{ validator_repo }}"
        dest: "/opt/kepler"
        version: main
        force: yes

    - name: Create validator.yaml
      copy:
        dest: "{{ validator_yaml_path }}"
        content: |
          log_level: info
          remote:
            host: my-vm
            username: root
            pkey: /tmp/vm_ssh_key
          metal:
            vm:
              name: my-vm
          prometheus:
            job:
              metal: metal
              vm: vm
            url: http://localhost:9090
            rate_interval: 20s
            steps: 5s
          validations_file: ./validations.yaml

    - name: Run the validator
      shell: |
        cd {{ validator_dir }}
        hatch run validator stress
