---
- name: Deploy and run the Kepler Validator
  hosts: localhost
  become: yes
  vars:
    validator_repo: "https://github.com/sustainable-computing-io/kepler.git"
    validator_dir: "/opt/kepler/e2e/tools/validator/src"
    validator_yaml_path: "/opt/kepler/e2e/tools/validator/src/validator.yaml"
    stress_test_script_path: "/opt/kepler/e2e/tools/validator/scripts/stressor.sh"
    query_json_path: "/opt/kepler/e2e/tools/validator/query.json"

  tasks:
    - name: yum install stress-ng, git and python3.11
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - python3.11
        - python3.11-pip
        - stress-ng

    - name: Clone the Kepler repository
      ignore_errors: true
      git:
        repo: "{{ validator_repo }}"
        dest: "/opt/kepler"
        version: main
        force: false

    - name: Create validator.yaml
      copy:
        dest: "{{ validator_yaml_path }}"
        content: |
          log_level: info
          remote:
            host: my-vm
            username: root
            pkey: /tmp/vm_ssh_key
          metal:
            vm:
              name: my-vm
          prometheus:
            job:
              metal: metal
              vm: vm
            url: http://localhost:9090
            rate_interval: 20s
            steps: 5s
          stressor:
            total_runtime_seconds: {{ lookup('env', 'TOTAL_RUNTIME_SECONDS') }}
            curve_type: {{ lookup('env', 'VALIDATOTR_CURVE_TYPE') }}
          validations_file: ../validations.yaml

    - name: Install the validator
      shell: |
        cd {{ validator_dir }}
        pip3.11 install ..

    - name: Run the validator
      shell: |
        cd {{ validator_dir }}
        PYTHONPATH=${PYTHONPATH}:./ python3.11 validator/__main__.py stress -s {{ stress_test_script_path }}
      args:
        chdir: "{{ validator_dir }}"
