---
- name: Setup Environment
  hosts: "localhost"
  become: yes
  vars:
    ansible_user: root
  roles:
    - docker
    - kepler_compose
  any_errors_fatal: true

- name: Run validator
  hosts: "localhost"
  become: yes
  vars:
  roles:
    - validator
  any_errors_fatal: true
