name: Cleanup

on:
  workflow_call:
    inputs:
      runner_name:
        required: true
        type: string

jobs:
  Cleanup:
    name: "Cleanup"
    runs-on: ubuntu-latest

    steps:
      - name: delete runner
        uses: sustainable-computing-io/metal-sweeper-action@main
        with:
          authToken: ${{ secrets.EQUINIX_API_TOKEN }}
          projectID: ${{ secrets.EQUINIX_PROJECT_ID }}
          runnerName: ${{ inputs.runner_name }}