name: Create Runner

on:
  workflow_call:
    inputs:
      os_name:
        description: "Name of the OS to be requested for the runner"
        required: false
        type: string
        default: "rhel_9"

jobs:
  Create-runner:
    name: "Create Runner"
    runs-on: ubuntu-latest

    steps:
      - name: metal-runner-action
        uses: equinix-labs/metal-runner-action@v0.4.0
        with:
          github_token: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
          metal_auth_token: ${{ secrets.EQUINIX_API_TOKEN }}
          metal_project_id: ${{ secrets.EQUINIX_PROJECT_ID }}
          metro: "da"
          plan: "m2.xlarge.x86"
          os: "${{ inputs.os_name }}"
