name: Equinix Metal Trainer

on:
  workflow_dispatch:
  workflow_call:

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write

jobs:
  Create-runner:
    name: "Create Runner"
    uses: ./.github/workflows/create_equinix_runner.yml
    secrets: inherit

  Train-models:
    name: "Train Models"
    needs: Create-runner
    runs-on: self-hosted
    continue-on-error: true
    outputs:
      runner-name: ${{ runner.name }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Setup Runner Action
        uses: ./.github/actions/setup-action

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Baremetal Setup
        run: |
          cd ${GITHUB_WORKSPACE}/ansible
          echo "Install Prometheus Baremetal"
          ansible-playbook -i inventory.yml -vvv metal_prometheus.yml
          echo "Install Kepler Metal"
          ansible-playbook -i inventory.yml kepler_playbook.yml -e "target_host=localhost"      

      - name: Run Trainer Action
        uses: ./.github/actions/train-action
        with:
          model_export_path: /tmp/trained-equinix-models

  Cleanup:
    name: "Cleanup"
    needs: [Train-models]
    uses: ./.github/workflows/clean_equinix_runner.yml
    secrets: inherit
    with:
      runner_name: ${{ needs.Train-models.outputs.runner-name }}