name: Equinix k8s Provisioning

on:
  workflow_dispatch:
    inputs:
      termination_time:
        description: 'Cluster termination time in hours after now'
        required: true
        default: '1'
      control_plan:
        description: 'control plane machine type'
        required: false
        default: 'c3.small.x86'
      node_plan:
        description: 'node machine type'
        required: false
        default: 'c3.small.x86'
      metro:
        description: 'metro location'
        required: false
        default: 'da'


jobs:
  Create-k8s-cluster:
    name: "Create Cluster"
    uses: ./.github/workflows/create_equinix_k8s_cluster.yml
    secrets: inherit
    with:
      termination_time: ${{ github.event.inputs.termination_time || '1' }}
      control_plan: ${{ github.event.inputs.control_plan }}
      node_plan: ${{ github.event.inputs.node_plan }}
      metro: ${{ github.event.inputs.metro }}

  Test-K8s:
    name: "Test K8s"
    needs: Create-k8s-cluster
    runs-on: ubuntu-latest

    steps:
      - name: Config kube
        uses: ./.github/actions/kube_config
        with:
          ## kube config
          artifact_name: kubeconfig-${{ github.run_id }}
      - name: Set up Kepler
        uses: ./.github/actions/setup_kepler
      