name: Equinix Metal Flow Compose

on:
  push:
    branches:
      - add-dk-w

jobs:
  create-runner:
    name: "Create Runner"
    runs-on: ubuntu-latest

    steps:
      - name: metal-runner-action
        uses: rootfs/metal-runner-action@main
        with:
          github_token: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
          metal_auth_token: ${{ secrets.EQUINIX_API_TOKEN }}
          metal_project_id: ${{ secrets.EQUINIX_PROJECT_ID }}
          metro: "da"
          plan: "c3.small.x86"
          os: "rhel_9"

  setup-runner:
    name: "Setup Runner"
    needs: create-runner
    runs-on: self-hosted
    continue-on-error: true
    outputs:
      runner-name: ${{ runner.name }}

    steps:
      - name: Setup runner
        run: |
          echo "Runner: ${{ runner.name }}"
          echo "OS: ${{ runner.os }}"
          # config ssh
          sudo ssh-keygen -t rsa -b 4096 -f /root/.ssh/ansible_rsa -N ''
          sudo cat ~/.ssh/ansible_rsa.pub >> ~/.ssh/authorized_keys
          sudo echo "StrictHostKeyChecking no" >> ~/.ssh/config
          # install ansible
          sudo dnf -y install ansible-core python3-pip
          sudo dnf install -y rhel-system-roles
          sudo ansible-galaxy collection install community.crypto

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run playbook
        run: |
          cd ${GITHUB_WORKSPACE}/ansible
          echo "Launch dev compose"
          ansible-playbook -i inventory.yml kepler_dev_compose_playbook.yml

  cleanup:
    name: "Cleanup"
    runs-on: ubuntu-latest
    needs: [setup-runner]

    steps:
      - name: delete runner
        uses: rootfs/metal-delete-action@main
        with:
          authToken: ${{ secrets.EQUINIX_API_TOKEN }}
          projectID: ${{ secrets.EQUINIX_PROJECT_ID }}
          runnerName: ${{ needs.setup-runner.outputs.runner-name }}
